-- KHA Mobile / Elegant Gadget Emporium — core schema (PostgreSQL 14+)
-- Apply: psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f sql/001_schema.sql

BEGIN;

-- ---------------------------------------------------------------------------
-- Admin accounts (passwords stored as bcrypt hashes; never commit real prod
-- passwords; use 002_seed_admin.sql only in local/dev).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(255),
  role VARCHAR(50) NOT NULL DEFAULT 'admin',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_admin_users_email ON admin_users (LOWER(email));

-- ---------------------------------------------------------------------------
-- Key/value settings (catalog mode, feature flags, contact info, etc.)
-- Example: INSERT INTO site_settings(key, value) VALUES ('catalog', '{"mode":"merge"}');
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS site_settings (
  key VARCHAR(100) PRIMARY KEY,
  value JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Products managed by admin (JSONB mirrors frontend Product / GreenLion shape).
-- legacy_override_id: when set, merged storefront replaces static product
-- with the same numeric id (price, copy, images from DB).
-- New-only rows: leave legacy_override_id NULL; ids start at 100000 by default.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS products (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1),
  legacy_override_id INTEGER UNIQUE,
  name VARCHAR(500) NOT NULL,
  title VARCHAR(500) NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  price NUMERIC(12, 2) NOT NULL,
  primary_image_url TEXT NOT NULL,
  rating NUMERIC(3, 2) NOT NULL DEFAULT 4.50,
  category VARCHAR(120) NOT NULL,
  brand VARCHAR(200),
  video_url TEXT,
  is_preorder BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  features JSONB NOT NULL DEFAULT '[]'::jsonb,
  specifications JSONB NOT NULL DEFAULT '[]'::jsonb,
  variants JSONB NOT NULL DEFAULT '[]'::jsonb,
  colors JSONB NOT NULL DEFAULT '[]'::jsonb,
  sizes JSONB NOT NULL DEFAULT '[]'::jsonb,
  connectivity_options JSONB NOT NULL DEFAULT '[]'::jsonb,
  secondary_categories JSONB NOT NULL DEFAULT '[]'::jsonb,
  gallery_images JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT products_price_non_negative CHECK (price >= 0),
  CONSTRAINT products_rating_range CHECK (rating >= 0 AND rating <= 5)
);

CREATE INDEX IF NOT EXISTS idx_products_category ON products (category);
CREATE INDEX IF NOT EXISTS idx_products_active ON products (is_active);
CREATE INDEX IF NOT EXISTS idx_products_legacy_override
  ON products (legacy_override_id)
  WHERE legacy_override_id IS NOT NULL;

COMMIT;
