-- KHA Mobile – Full Product Seed
-- Run AFTER 001_schema.sql and 002_seed_admin.sql
-- NOTE: Images use placeholder URLs. Update them through the Admin panel
--       (Admin → Products → Edit → Upload primary / gallery images).
--       The legacy_override_id matches each product's static ID so the
--       database version OVERRIDES the static TypeScript version.

BEGIN;

-- ─────────────────────────────────────────────────────────────────────────────
-- COMPUTERS (ids 11-15, static from allProducts.ts, Unsplash images)
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO products (legacy_override_id, name, title, description, price, primary_image_url, rating, category, brand, is_active, features, specifications)
VALUES
(11, 'MacBook Pro 16', 'MacBook Pro 16-inch', 'The most powerful MacBook Pro ever. Supercharged by M-series chip for exceptional performance and battery life.', 2499, 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500&h=500&fit=crop', 4.9, 'Computers', 'Apple', true, '["M-series chip","16-inch Liquid Retina XDR display","Up to 22 hours battery","Up to 128GB unified memory","ProRes video support","MagSafe 3 charging"]', '[{"label":"Display","value":"16-inch Liquid Retina XDR"},{"label":"Chip","value":"Apple M-series"},{"label":"Battery","value":"Up to 22 hours"},{"label":"Memory","value":"Up to 128GB unified"},{"label":"Storage","value":"Up to 8TB SSD"}]'),
(12, 'Dell XPS 15', 'Dell XPS 15 Laptop', 'Premium 15-inch laptop with OLED display, Intel Core processor, and thin & light design for professionals.', 1899, 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=500&h=500&fit=crop', 4.7, 'Computers', 'Dell', true, '["Intel Core i7/i9 processor","15.6-inch OLED display","NVIDIA GeForce RTX graphics","Up to 86Wh battery","Thunderbolt 4 ports","Fingerprint reader"]', '[{"label":"Display","value":"15.6-inch OLED"},{"label":"Processor","value":"Intel Core i7/i9"},{"label":"Graphics","value":"NVIDIA GeForce RTX"},{"label":"Battery","value":"86Wh"},{"label":"Ports","value":"Thunderbolt 4"}]'),
(13, 'HP Spectre x360', 'HP Spectre x360 Convertible Laptop', 'Ultra-premium 2-in-1 convertible laptop with OLED display, Intel Evo platform, and gem-cut design.', 1299, 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=500&h=500&fit=crop', 4.6, 'Computers', 'HP', true, '["Intel Evo platform","OLED 2-in-1 convertible","360-degree hinge","Intel Iris Xe graphics","Fingerprint reader","Bang & Olufsen audio"]', '[{"label":"Type","value":"2-in-1 Convertible"},{"label":"Platform","value":"Intel Evo"},{"label":"Display","value":"OLED"},{"label":"Hinge","value":"360-degree"},{"label":"Audio","value":"Bang & Olufsen"}]'),
(14, 'Lenovo ThinkPad X1 Carbon', 'Lenovo ThinkPad X1 Carbon', 'Business ultrabook with legendary ThinkPad reliability, Intel Core Ultra processor, and military-grade durability.', 1499, 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=500&h=500&fit=crop', 4.8, 'Computers', 'Lenovo', true, '["Intel Core Ultra processor","14-inch IPS display","Military-grade durability (MIL-STD-810H)","Up to 15 hours battery","Thunderbolt 4","ThinkPad keyboard"]', '[{"label":"Processor","value":"Intel Core Ultra"},{"label":"Display","value":"14-inch IPS"},{"label":"Durability","value":"MIL-STD-810H"},{"label":"Battery","value":"Up to 15 hours"},{"label":"Keyboard","value":"ThinkPad backlit"}]'),
(15, 'ASUS ROG Zephyrus', 'ASUS ROG Zephyrus Gaming Laptop', 'Powerful gaming laptop with AMD Ryzen processor, NVIDIA RTX graphics, and high-refresh display for competitive gaming.', 1999, 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500&h=500&fit=crop', 4.7, 'Computers', 'ASUS', true, '["AMD Ryzen 9 processor","NVIDIA GeForce RTX 4090","165Hz QHD display","ROG Intelligent Cooling","Dolby Atmos audio","USB-C charging"]', '[{"label":"Processor","value":"AMD Ryzen 9"},{"label":"GPU","value":"NVIDIA RTX 4090"},{"label":"Display","value":"165Hz QHD"},{"label":"Cooling","value":"ROG Intelligent Cooling"},{"label":"Audio","value":"Dolby Atmos"}]')
ON CONFLICT (legacy_override_id) DO UPDATE SET
  name=EXCLUDED.name, title=EXCLUDED.title, description=EXCLUDED.description,
  price=EXCLUDED.price, primary_image_url=EXCLUDED.primary_image_url,
  rating=EXCLUDED.rating, category=EXCLUDED.category, brand=EXCLUDED.brand,
  features=EXCLUDED.features, specifications=EXCLUDED.specifications,
  updated_at=NOW();

-- ─────────────────────────────────────────────────────────────────────────────
-- PHONE ACCESSORIES (power banks, stands, chargers)
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO products (legacy_override_id, name, title, description, price, primary_image_url, rating, category, brand, is_active, features, specifications, secondary_categories)
VALUES
(101, 'Hoco Q37 IntelligentBalance 10000mAh Power Bank', 'Hoco Q37 Fast Charging Power Bank (10000mAh)', 'Stay powered up wherever you go with the Hoco Q37 IntelligentBalance Power Bank. Features built-in cables, 22.5W fast charging, and a digital display showing remaining battery percentage.', 20, 'https://placehold.co/500x500/0f172a/ffffff?text=Hoco+Q37', 4.8, 'Charging', 'Hoco', true, '["10000mAh Capacity","22.5W, PD 20W, QC3.0 Fast Charging","Built-in Lightning and USB-C cables","4 outputs, 2 inputs","Digital battery percentage display","18-Month Warranty"]', '[{"label":"Capacity","value":"10000mAh"},{"label":"Fast Charging","value":"22.5W, PD 20W, QC3.0"},{"label":"Outputs","value":"4"},{"label":"Inputs","value":"2"},{"label":"Built-in Cables","value":"Lightning, USB-C"},{"label":"Display","value":"Digital Battery Percentage"}]', '["Accessories"]'),
(102, 'Dobe Dual Charging Dock for PS4 Controllers', 'Dobe Dual Charging Dock for PlayStation 4 Controllers', 'Keep your gaming sessions uninterrupted with the Dobe Dual Charging Dock for PS4. Charges two DUALSHOCK 4 controllers simultaneously with LED charging indicators.', 10, 'https://placehold.co/500x500/0f172a/ffffff?text=Dobe+PS4+Dock', 4.7, 'Gaming', 'Dobe', true, '["Dual Controller Charging","Compatible with PS4, PS4 Slim, PS4 Pro","LED charging indicators","Stable dock design","Easy drop-in charging"]', '[{"label":"Compatibility","value":"PS4, PS4 Slim, PS4 Pro"},{"label":"Capacity","value":"2 controllers"},{"label":"Indicators","value":"LED status"}]', '["Gaming Accessories"]'),
(103, 'Dobe Charging Dock for PS5 Controllers', 'Dobe Charging Dock for PlayStation 5 DualSense Controllers', 'Power up your next-gen gaming with the Dobe Charging Dock for PS5. Charges two DualSense controllers with overcharge protection and PS5-matching design.', 10, 'https://placehold.co/500x500/0f172a/ffffff?text=Dobe+PS5+Dock', 4.8, 'Gaming', 'Dobe', true, '["Charges 2 DualSense controllers","PS5 aesthetic design","Overcharge protection","Click-in secure connection","Compact design"]', '[{"label":"Compatibility","value":"PS5 DualSense"},{"label":"Capacity","value":"2 controllers"},{"label":"Protection","value":"Overcharge protection"}]', '["Gaming Accessories"]'),
(104, 'Hoco J132A IntelligentBalance 20000mAh Power Bank', 'Hoco J132A High-Capacity Power Bank (20000mAh)', 'High-capacity 20000mAh powerhouse with 4-in-1 built-in cables, 22.5W fast charging, and LED digital display. Ideal for heavy users and travelers.', 30, 'https://placehold.co/500x500/0f172a/ffffff?text=Hoco+J132A', 4.9, 'Charging', 'Hoco', true, '["20000mAh Capacity","4-in-1 Built-in Cables (USB-C, Lightning, Micro-USB, USB-A)","22.5W Super Fast + PD 20W Charging","LED Digital Display","Charge up to 4 devices at once"]', '[{"label":"Capacity","value":"20000mAh"},{"label":"Fast Charging","value":"22.5W, PD 20W"},{"label":"Built-in Cables","value":"USB-C, Lightning, Micro-USB, USB-A"},{"label":"Display","value":"LED Digital"}]', '["Accessories"]'),
(105, 'Kakusiga Folding Rotatable Desktop Stand', 'Kakusiga 360° Rotatable Folding Desktop Stand', 'Versatile 360° rotating phone stand with adjustable height and angle. Foldable for travel, compatible with 4.7-7 inch devices.', 10, 'https://placehold.co/500x500/0f172a/ffffff?text=Kakusiga+Stand', 4.6, 'Accessories', 'Kakusiga', true, '["360° Rotating Base","Fully Foldable Design","Adjustable Height & Angle","Weighted non-slip base","Universal 4.7-7 inch compatibility"]', '[{"label":"Rotation","value":"360°"},{"label":"Design","value":"Foldable"},{"label":"Compatibility","value":"4.7\" to 7\" devices"}]', '["Phone Accessories"]'),
(109, '25W USB-C Power Adapter with USB-C to Lightning Cable', '25W USB-C Fast Charger Set (Adapter & Cable)', 'Complete fast charging set with 25W USB-C power adapter and USB-C to Lightning cable. Fast-charges iPhone to 50% in ~30 minutes.', 15, 'https://placehold.co/500x500/0f172a/ffffff?text=25W+USB-C+Set', 4.8, 'Charging', 'Apple', true, '["25W Fast Charging","Complete set: adapter + USB-C to Lightning cable","Compatible with iPhone 14/13/12/11 Pro/Pro Max","Compact portable design"]', '[{"label":"Power","value":"25W"},{"label":"Cable","value":"USB-C to Lightning"},{"label":"Compatibility","value":"iPhone 14/13/12/11"}]', '["Accessories"]'),
(112, 'Hoco 22.5W 10000mAh Power Bank', 'Hoco 22.5W Super Fast Charging Power Bank (10000mAh)', 'Compact 10000mAh power bank with 22.5W super fast charging. Charges smartphone to 50% in under 30 minutes. Multiple port support.', 20, 'https://placehold.co/500x500/0f172a/ffffff?text=Hoco+22.5W', 4.8, 'Charging', 'Hoco', true, '["22.5W Super Fast Charging","10000mAh capacity","Multiple outputs","LED battery indicator","Compact design"]', '[{"label":"Capacity","value":"10000mAh"},{"label":"Fast Charging","value":"22.5W"},{"label":"Design","value":"Compact"}]', '["Accessories"]')
ON CONFLICT (legacy_override_id) DO UPDATE SET
  name=EXCLUDED.name, title=EXCLUDED.title, description=EXCLUDED.description,
  price=EXCLUDED.price, primary_image_url=EXCLUDED.primary_image_url,
  rating=EXCLUDED.rating, category=EXCLUDED.category, brand=EXCLUDED.brand,
  features=EXCLUDED.features, specifications=EXCLUDED.specifications,
  secondary_categories=EXCLUDED.secondary_categories, updated_at=NOW();

-- ─────────────────────────────────────────────────────────────────────────────
-- AUDIO PRODUCTS
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO products (legacy_override_id, name, title, description, price, primary_image_url, rating, category, brand, is_active, features, specifications)
VALUES
(106, 'Apple AirPods', 'Apple AirPods with MagSafe Charging Case', 'Experience the magic of Apple AirPods with Spatial Audio, dynamic head tracking, and a contoured design. Over 30 hours total listening time with MagSafe case.', 10, 'https://placehold.co/500x500/0f172a/ffffff?text=AirPods', 4.9, 'Audio', 'Apple', true, '["Spatial Audio with dynamic head tracking","Adaptive EQ","Contoured ergonomic design","Force sensor controls","IPX4 sweat & water resistant","30+ hours total with MagSafe case","MagSafe & wireless charging","12-Month warranty"]', '[{"label":"Audio","value":"Spatial Audio"},{"label":"EQ","value":"Adaptive EQ"},{"label":"Resistance","value":"IPX4"},{"label":"Battery","value":"30+ hours total"},{"label":"Charging","value":"MagSafe, wireless"}]'),
(107, 'Galaxy Buds6 Pro (White)', 'Samsung Galaxy Buds6 Pro Wireless Earbuds - White', 'Samsung Galaxy Buds6 Pro in White. True wireless earbuds with ergonomic fit, touch controls, and built-in microphone for hands-free calls.', 15, 'https://placehold.co/500x500/0f172a/ffffff?text=Galaxy+Buds6+White', 4.7, 'Audio', 'Samsung', true, '["True Wireless Design","Ergonomic fit","Touch controls","Built-in microphone","Compact charging case","Bluetooth connectivity"]', '[{"label":"Color","value":"White"},{"label":"Design","value":"True wireless"},{"label":"Controls","value":"Touch"},{"label":"Mic","value":"Built-in"}]'),
(108, 'Galaxy Buds6 Pro (Black)', 'Samsung Galaxy Buds6 Pro Wireless Earbuds - Black', 'Samsung Galaxy Buds6 Pro in Black. True wireless earbuds with ergonomic fit, touch controls, and built-in microphone for hands-free calls.', 15, 'https://placehold.co/500x500/0f172a/ffffff?text=Galaxy+Buds6+Black', 4.7, 'Audio', 'Samsung', true, '["True Wireless Design","Ergonomic fit","Touch controls","Built-in microphone","Compact charging case","Bluetooth connectivity"]', '[{"label":"Color","value":"Black"},{"label":"Design","value":"True wireless"},{"label":"Controls","value":"Touch"},{"label":"Mic","value":"Built-in"}]'),
(110, 'JBL Tune 903BT V5.3 Wireless Headphone', 'JBL Tune 903BT V5.3 Wireless Over-Ear Headphone', 'Premium JBL Pure Bass sound with Bluetooth 5.3. 40 hours battery life, 10-min quick charge for 4 hours, multi-point connection, and built-in microphone.', 16, 'https://placehold.co/500x500/0f172a/ffffff?text=JBL+903BT', 4.7, 'Audio', 'JBL', true, '["Bluetooth 5.3","JBL Pure Bass Sound","Up to 40 hours battery","Quick charge: 10min = 4hrs","Multi-point connection","Built-in microphone","Foldable design"]', '[{"label":"Bluetooth","value":"5.3"},{"label":"Battery","value":"40 hours"},{"label":"Quick Charge","value":"10min = 4hrs"},{"label":"Connection","value":"Multi-point"}]'),
(111, 'Apple AirPods 4 (Copy A)', 'Apple AirPods 4 (Copy A) - H2 Chip Sound Experience', 'High-quality AirPods 4 replica featuring the H2 chip experience with Spatial Audio, Personalized Spatial Audio, Adaptive EQ, and MagSafe charging. IPX4 resistance.', 20, 'https://placehold.co/500x500/0f172a/ffffff?text=AirPods+4+Copy', 4.9, 'Audio', 'Apple', true, '["H2 Chip audio processing","Spatial Audio with dynamic head tracking","Personalized Spatial Audio","Adaptive EQ","IPX4 sweat & water resistant","MagSafe charging case","30+ hours total battery","Available with ANC option"]', '[{"label":"Chip","value":"H2"},{"label":"Audio","value":"Spatial Audio"},{"label":"Resistance","value":"IPX4"},{"label":"Battery","value":"30+ hours total"},{"label":"Charging","value":"MagSafe"}]'),
(127, 'Apple AirPods Pro 3', 'Apple AirPods Pro 3 - White (AAP3-WT)', 'Next-gen AirPods Pro 3 with heart rate sensing, studio-quality recording, ANC with Adaptive Audio, IP57 water resistance, up to 32 hours total battery, and USB-C charging.', 287, 'https://placehold.co/500x500/0f172a/ffffff?text=AirPods+Pro+3', 5.0, 'Audio', 'Apple', true, '["Heart Rate Sensing","Workout Tracking (50+ types)","Studio-quality recording","ANC with Adaptive Audio","Adaptive Transparency","Personalized Spatial Audio","8hrs (ANC) + 24hrs case = 32hrs total","IP57 water resistance","Bluetooth 5.4","USB-C charging"]', '[{"label":"Model","value":"AAP3-WT (White)"},{"label":"Bluetooth","value":"5.4"},{"label":"Battery (ANC)","value":"8 hours"},{"label":"Battery (Case)","value":"24 hours"},{"label":"Total Battery","value":"32 hours"},{"label":"Charging","value":"USB-C + wireless"},{"label":"Water Resistance","value":"IP57"}]'),
(128, 'Apple AirPods 4 (Original)', 'Apple AirPods 4 (Original) - Official', 'Official Apple AirPods 4 with H2 chip, Personalized Spatial Audio, Adaptive EQ, IP54 resistance, USB-C charging, and up to 30 hours total battery. Available in Standard and ANC variants.', 150, 'https://placehold.co/500x500/0f172a/ffffff?text=AirPods+4+Original', 4.9, 'Audio', 'Apple', true, '["Apple H2 Chip","Redesigned ergonomic fit","Personalized Spatial Audio","Adaptive EQ","Voice Isolation for calls","IP54 (earbuds + case)","USB-C charging","Force sensor controls","Hey Siri always-on","Bluetooth 5.3","Find My support"]', '[{"label":"Chip","value":"Apple H2"},{"label":"Resistance","value":"IP54 earbuds + case"},{"label":"Battery","value":"30 hours total"},{"label":"Charging","value":"USB-C"},{"label":"Bluetooth","value":"5.3"},{"label":"In Box","value":"AirPods 4, USB-C case, documentation"}]'),
(129, 'Apple AirPods Pro (2nd Generation) with USB-C', 'Apple AirPods Pro (2nd Generation) - USB-C Charging', 'Premium AirPods Pro 2 with H2 chip, 2x ANC, Adaptive Audio, Conversation Awareness, Personalized Spatial Audio, hearing health features, 30hrs total battery, and IP54 USB-C case.', 215, 'https://placehold.co/500x500/0f172a/ffffff?text=AirPods+Pro+2+USBC', 5.0, 'Audio', 'Apple', true, '["Apple H2 Chip","Up to 2x Active Noise Cancellation","Adaptive Audio","Conversation Awareness","Personalized Spatial Audio","Hearing Test & Hearing Aid features","6hrs (ANC) + 24hrs case = 30hrs total","IP54 (earbuds + case)","USB-C MagSafe case","Bluetooth 5.3","Lossless audio for Vision Pro"]', '[{"label":"Chip","value":"Apple H2"},{"label":"ANC","value":"2x improvement"},{"label":"Battery (ANC)","value":"6 hours"},{"label":"Total Battery","value":"30 hours"},{"label":"Charging","value":"USB-C, MagSafe, Qi, Apple Watch charger"},{"label":"Resistance","value":"IP54 (earbuds + case)"},{"label":"Bluetooth","value":"5.3"}]'),
(140, 'JBL TUNE110 Earphones', 'JBL TUNE110 In-Ear Headphones with Pure Bass Sound', 'Lightweight JBL TUNE110 in-ear headphones with 9mm drivers for JBL Pure Bass sound. Tangle-free flat cable with single-button remote and microphone. Available in Black, Blue, White.', 10, 'https://placehold.co/500x500/0f172a/ffffff?text=JBL+TUNE110', 4.5, 'Audio', 'JBL', true, '["JBL Pure Bass Sound","1-Button remote with microphone","Tangle-free flat cable","9mm drivers","Lightweight & compact","3.5mm jack connection"]', '[{"label":"Driver","value":"9.0mm"},{"label":"Frequency","value":"20Hz–20kHz"},{"label":"Connection","value":"3.5mm Jack"},{"label":"Cable","value":"Tangle-free flat"}]'),
(141, 'JBL Tune 520BT Wireless Headphones', 'JBL Tune 520BT Wireless On-Ear Headphones', 'JBL Pure Bass wireless headphones with Bluetooth 5.3, up to 57 hours battery, 5-minute quick charge for 3 hours, multi-point connection, and voice assistant support.', 45, 'https://placehold.co/500x500/0f172a/ffffff?text=JBL+520BT', 4.7, 'Audio', 'JBL', true, '["JBL Pure Bass Sound","Bluetooth 5.3","57 hours battery life","Quick Charge: 5min = 3hrs","Multi-point connection","Voice aware feature","Siri/Google Assistant","Foldable lightweight design"]', '[{"label":"Bluetooth","value":"5.3"},{"label":"Driver","value":"33mm"},{"label":"Battery","value":"57 hours"},{"label":"Charging","value":"2 hours"},{"label":"Weight","value":"157g"},{"label":"Impedance","value":"30 ohm"}]'),
(142, 'JBL Tune 720BT Wireless Headphones', 'JBL Tune 720BT Wireless Over-Ear Headphones', 'JBL Pure Bass over-ear wireless headphones with Bluetooth 5.3, up to 76 hours battery, 5-minute quick charge, multi-point connection, and JBL Headphones App support.', 57, 'https://placehold.co/500x500/0f172a/ffffff?text=JBL+720BT', 4.8, 'Audio', 'JBL', true, '["JBL Pure Bass Sound","Bluetooth 5.3","76 hours battery life","Quick Charge: 5min = 3hrs","Multi-point connection","JBL Headphones App support","Voice Aware","Foldable lightweight design"]', '[{"label":"Bluetooth","value":"5.3"},{"label":"Driver","value":"40mm"},{"label":"Battery","value":"76 hours"},{"label":"Charging","value":"2 hours"},{"label":"Weight","value":"220g"},{"label":"Impedance","value":"32 ohm"}]'),
(143, 'JBL Go 4 Ultra-Portable Bluetooth Speaker', 'JBL Go 4 Ultra-Portable Waterproof Bluetooth Speaker', 'Palm-sized IP67 waterproof Bluetooth 5.3 speaker with clear JBL Pro Sound, up to 7 hours playtime, redesigned loop, stereo pairing, and vibrant color options.', 60, 'https://placehold.co/500x500/0f172a/ffffff?text=JBL+Go+4', 4.9, 'Audio', 'JBL', true, '["Ultra-portable JBL Pro Sound","7 hours playtime","IP67 waterproof & dustproof","Bluetooth 5.3","Stereo pairing (2 Go 4s)","Auracast multi-speaker","Redesigned integrated loop","Made with recycled materials"]', '[{"label":"Output","value":"4.2W"},{"label":"Frequency","value":"90Hz–20kHz"},{"label":"Bluetooth","value":"5.3"},{"label":"Battery","value":"7 hours"},{"label":"Charging","value":"3 hours"},{"label":"Rating","value":"IP67"},{"label":"Weight","value":"0.19kg"}]'),
(144, 'JBL PartyBox Club 120', 'JBL PartyBox Club 120 Portable Speaker with Lights', 'Party speaker with 160W JBL Pro Sound, starry light show synced to music, mic & guitar inputs, replaceable battery, 12 hours playtime, IPX4, and AI Sound Boost.', 370, 'https://placehold.co/500x500/0f172a/ffffff?text=JBL+PartyBox+120', 4.9, 'Audio', 'JBL', true, '["160W Powerful JBL Pro Sound","Futuristic lightshow (starry lights, strobe)","12 hours playtime","Replaceable battery","Mic & guitar inputs","IPX4 splashproof","AI Sound Boost","Stereo pairing & Auracast multi-speaker","JBL PartyBox App"]', '[{"label":"Output","value":"160W"},{"label":"Frequency","value":"40Hz–20kHz"},{"label":"Bluetooth","value":"5.3"},{"label":"Battery","value":"12 hours"},{"label":"Charging","value":"3.5 hours"},{"label":"Rating","value":"IPX4"},{"label":"Weight","value":"11.05kg"}]')
ON CONFLICT (legacy_override_id) DO UPDATE SET
  name=EXCLUDED.name, title=EXCLUDED.title, description=EXCLUDED.description,
  price=EXCLUDED.price, primary_image_url=EXCLUDED.primary_image_url,
  rating=EXCLUDED.rating, category=EXCLUDED.category, brand=EXCLUDED.brand,
  features=EXCLUDED.features, specifications=EXCLUDED.specifications, updated_at=NOW();

-- ─────────────────────────────────────────────────────────────────────────────
-- iPHONE 16
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO products (legacy_override_id, name, title, description, price, primary_image_url, rating, category, brand, is_active, features, specifications, variants, colors)
VALUES (
  500,
  'iPhone 16',
  'iPhone 16 - Built for Apple Intelligence',
  'iPhone 16 is built for Apple Intelligence. Featuring the A18 chip, Camera Control, 48MP Fusion camera, Ceramic Shield (2x tougher), and all-day battery life.',
  780,
  'https://placehold.co/500x500/0f172a/ffffff?text=iPhone+16',
  5.0,
  'Smartphones',
  'Apple',
  true,
  '["Apple Intelligence built-in","A18 chip (6-core CPU, 5-core GPU, 16-core Neural Engine)","Camera Control for instant camera access","48MP Fusion camera (f/1.6) + 12MP Ultra Wide","2x Telephoto at 52mm","4K Dolby Vision up to 60fps","Super Retina XDR 6.1-inch OLED","Dynamic Island","Ceramic Shield (2x tougher)","Up to 22 hours video playback","MagSafe up to 25W, Qi2 15W","5G & Wi-Fi 7","Face ID","Emergency SOS via Satellite","Crash Detection","iOS 18"]',
  '[{"label":"Model","value":"iPhone 16"},{"label":"Chip","value":"A18 (6-core CPU, 5-core GPU, 16-core NE)"},{"label":"Display","value":"6.1-inch Super Retina XDR OLED, 460 ppi"},{"label":"Rear Camera","value":"48MP Fusion + 12MP Ultra Wide"},{"label":"Telephoto","value":"12MP 2x at 52mm"},{"label":"Video","value":"4K Dolby Vision up to 60fps"},{"label":"Battery","value":"Up to 22 hours video"},{"label":"Charging","value":"MagSafe 25W, Qi2 15W"},{"label":"5G","value":"Sub-6GHz + mmWave"},{"label":"Wi-Fi","value":"Wi-Fi 7"},{"label":"Bluetooth","value":"5.3"},{"label":"Water","value":"IP68 (6m, 30min)"},{"label":"OS","value":"iOS 18"}]',
  '[{"key":"iphone16-128gb","ram":"","storage":"128GB","label":"128GB","price":780,"description":"Brand new iPhone 16 128GB."},{"key":"iphone16-256gb","ram":"","storage":"256GB","label":"256GB","price":920,"description":"Brand new iPhone 16 256GB."}]',
  '[{"name":"Ultramarine","stock":"available"},{"name":"Teal","stock":"available"},{"name":"Pink","stock":"available"},{"name":"White","stock":"available"},{"name":"Black","stock":"available"}]'
)
ON CONFLICT (legacy_override_id) DO UPDATE SET
  name=EXCLUDED.name, title=EXCLUDED.title, description=EXCLUDED.description,
  price=EXCLUDED.price, primary_image_url=EXCLUDED.primary_image_url,
  rating=EXCLUDED.rating, category=EXCLUDED.category, brand=EXCLUDED.brand,
  features=EXCLUDED.features, specifications=EXCLUDED.specifications,
  variants=EXCLUDED.variants, colors=EXCLUDED.colors, updated_at=NOW();

-- ─────────────────────────────────────────────────────────────────────────────
-- GREEN LION PRODUCTS (ids 5001-5035)
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO products (legacy_override_id, name, title, description, price, primary_image_url, rating, category, brand, is_active, features, specifications, secondary_categories)
VALUES
(5001,'Green Lion Hand Grip Strengthener','Green Lion Hand Grip Strengthener - Adjustable 5-60 Kg','Ergonomic hand grip strengthener for athletes and musicians. Adjustable 5-60 Kg resistance with built-in mechanical counter and digital indicator.',12,'https://placehold.co/500x500/0f172a/ffffff?text=GL+Hand+Grip',4.7,'Accessories','Green Lion',true,'["Adjustable resistance 5-60 Kg","Built-in mechanical counter","Ergonomic non-slip grip","High quality spring","Portable & durable","Digital indicator","ABS & Steel Spring material"]','[{"label":"Material","value":"ABS & Steel Spring"},{"label":"Resistance","value":"5-60 Kg"},{"label":"Counter","value":"Built-in mechanical"},{"label":"Grip","value":"Ergonomic Non-Slip"}]','["Fitness"]'),
(5002,'Green Lion Mini Massage Gun Pro 800mAh','Green Lion Mini Massage Gun Pro - 40W with 4 Speed Settings','Professional mini massage gun with 40W power, 4 speed settings, 800mAh battery, and <55dB quiet operation for deep tissue massage.',50,'https://placehold.co/500x500/0f172a/ffffff?text=GL+Massage+Gun',4.8,'Accessories','Green Lion',true,'["40W Max Rated Power","4 speed settings: 2200/2800/3600/4000 RPM","800mAh battery","1-3 hrs working time","<55dB noise level","Strong motor"]','[{"label":"Power","value":"40W Max"},{"label":"Battery","value":"800mAh"},{"label":"Speeds","value":"2200/2800/3600/4000 RPM"},{"label":"Working Time","value":"1-3 hours"},{"label":"Noise","value":"<55dB"}]','["Health & Wellness"]'),
(5003,'Green Lion Pro Trim Duo Hair Clipper','Green Lion Pro Trim Duo 9-in-1 Hair Clipper Set - Corded & Cordless','Professional 9-in-1 hair clipper set with hair + body clipper, digital display, carrying case, and multiple comb attachments. Corded & cordless.',55,'https://placehold.co/500x500/0f172a/ffffff?text=GL+Pro+Trim+Duo',4.9,'Accessories','Green Lion',true,'["9-in-1 complete set","Corded & cordless operation","Digital display","Hair clipper: 6800 RPM, 2000mAh, 2-3hrs","Body clipper: 7200 RPM, 1500mAh, 1.5-2.5hrs","Carrying case included","Taper lever","Type-C charging"]','[{"label":"Hair Clipper","value":"337 Motor, 6800 RPM, 2000mAh"},{"label":"Body Clipper","value":"280 Motor, 7200 RPM, 1500mAh"},{"label":"Hair Combs","value":"3/6/10/19 mm"},{"label":"Body Combs","value":"1/2/3 mm"},{"label":"Charging","value":"DC 5V 1A"},{"label":"Power","value":"8W"}]','["Grooming"]'),
(5004,'Green Lion Clip Pro Professional Hair Clipper','Green Lion Clip Pro Hair Clipper - 6000 RPM with LED Display','Professional hair clipper with 6000 RPM motor, stainless steel blade, LED display, and 180-minute working time. Type-C charging, corded & cordless.',28,'https://placehold.co/500x500/0f172a/ffffff?text=GL+Clip+Pro',4.7,'Accessories','Green Lion',true,'["6000 RPM powerful motor","180 min working time","Stainless steel blade","Corded & cordless","2000mAh battery","Type-C charging","LED display","Taper lever","5W power"]','[{"label":"Motor","value":"FF-337PA, 6000 RPM"},{"label":"Battery","value":"2000mAh"},{"label":"Working Time","value":"180 minutes"},{"label":"Blade","value":"Stainless Steel"},{"label":"Charging","value":"Type-C, 5V/1A"},{"label":"Power","value":"5W"}]','["Grooming"]'),
(5005,'Green Lion One Blade Beard Trimmer','Green Lion One Blade Beard Trimmer - IPX5 Waterproof, 120 Min Runtime','Waterproof IPX5 beard trimmer with stainless steel blade, 4 comb guards, 120-minute runtime, and Type-C charging.',25,'https://placehold.co/500x500/0f172a/ffffff?text=GL+One+Blade',4.6,'Accessories','Green Lion',true,'["120 minutes working time","Stainless steel blade with 4 comb guards","IPX5 waterproof","Type-C charging","86000 RPM motor","2 hour charging time"]','[{"label":"Motor","value":"86000 RPM"},{"label":"Battery","value":"3.7V 500mAh"},{"label":"Working Time","value":"120 minutes"},{"label":"Charging Time","value":"2 hours"},{"label":"Waterproof","value":"IPX5"},{"label":"Size","value":"156x38x28mm"},{"label":"Weight","value":"87.8g"}]','["Grooming"]'),
(5006,'Green Lion Pirates Hair Trimmer','Green Lion Pirates Hair Trimmer - LCD Display, 60 Min Runtime','Compact hair trimmer with LCD display, 6500 RPM motor, 60-minute runtime, and 600mAh battery. Perfect for travel.',27,'https://placehold.co/500x500/0f172a/ffffff?text=GL+Pirates+Trimmer',4.5,'Accessories','Green Lion',true,'["DC 3.7V 6500 RPM motor","60 min working time","2.5 hours charging","600mAh battery","LCD display"]','[{"label":"Motor","value":"DC 3.7V, 6500 RPM"},{"label":"Battery","value":"600mAh"},{"label":"Working Time","value":"60 minutes"},{"label":"Charging Time","value":"2.5 hours"},{"label":"Display","value":"LCD"}]','["Grooming"]'),
(5007,'Green Lion Glam Shine Makeup Mirror 9 LED Lights','Green Lion Glam Shine Makeup Mirror - 9 LED, 3 Color Modes, 360° Rotation','HD makeup mirror with 9 LED lights, 3 color temperatures (warm/cool/natural), touch control, and 360° rotation.',45,'https://placehold.co/500x500/0f172a/ffffff?text=GL+Mirror+9LED',4.8,'Accessories','Green Lion',true,'["9 LED lights","3 color modes: warm/cool/natural","360° rotation","Touch control","High definition mirror","USB-A to Type-C","5V=2A, 5±1W","Color temp: 3500k/6500k"]','[{"label":"LED Lights","value":"9 pcs"},{"label":"Color Temp","value":"3500k/6500k"},{"label":"Modes","value":"3 (Warm/Cool/Natural)"},{"label":"Power","value":"5V=2A, 5±1W"},{"label":"Rotation","value":"360°"}]','["Beauty"]'),
(5008,'Green Lion Glam Shine Makeup Mirror 12 LED Lights','Green Lion Glam Shine Makeup Mirror - 12 LED, 3 Color Modes, 360° Rotation','Premium HD makeup mirror with 12 LED lights for brighter illumination, 3 color temperatures, touch control, and 360° rotation.',55,'https://placehold.co/500x500/0f172a/ffffff?text=GL+Mirror+12LED',4.9,'Accessories','Green Lion',true,'["12 LED lights","3 color modes: warm/cool/natural","360° rotation","Touch control","High definition mirror","USB-A to Type-C","5V=2A, 5±1W"]','[{"label":"LED Lights","value":"12 pcs"},{"label":"Color Temp","value":"3500k/6500k"},{"label":"Modes","value":"3 (Warm/Cool/Natural)"},{"label":"Power","value":"5V=2A, 5±1W"},{"label":"Rotation","value":"360°"}]','["Beauty"]'),
(5009,'Green Lion Silkwave Straightener','Green Lion Silkwave Hair Straightener - 5 Temperature Settings, Ceramic Plates','Professional hair straightener with ceramic coating, 5 temperature settings (120-230°C), 360° swivel cord, and 1-hour auto-off.',44.99,'https://placehold.co/500x500/0f172a/ffffff?text=GL+Straightener',4.7,'Accessories','Green Lion',true,'["5 temperatures: 120-150-180-210-230°C","Ceramic coating plates","PTC heating element","360° swivel cord","1 hour auto off","On/off switch","Hang up loop"]','[{"label":"Temperature","value":"120-230°C (5 settings)"},{"label":"Plates","value":"Ceramic Coating"},{"label":"Heating","value":"PTC"},{"label":"Cord","value":"360° Swivel"},{"label":"Auto Off","value":"1 Hour"}]','["Beauty","Grooming"]'),
(5010,'Green Lion Blow Wave Hair Dryer 850W','Green Lion Blow Wave Hair Dryer - 850W, 2 Speed Settings, Ultra Quiet','Powerful 850W hair dryer with hot/cool wind, 2 speed settings, overheat protection, and ultra-quiet 74dB operation.',25,'https://placehold.co/500x500/0f172a/ffffff?text=GL+Hair+Dryer',4.6,'Accessories','Green Lion',true,'["850W rated power","Hot & cool wind","2 gear control","Overheat protection","74dB ultra quiet","6 m/s wind speed","Coiled heater","33-52°C temperature"]','[{"label":"Power","value":"850W"},{"label":"Voltage","value":"200-220V~"},{"label":"Temperature","value":"33-52°C"},{"label":"Wind Speed","value":"6 m/s"},{"label":"Noise","value":"74 dB"},{"label":"Speeds","value":"2"},{"label":"Safety","value":"Overheat protection"}]','["Beauty","Grooming"]'),
(5011,'Green Lion Digital Luggage Scale Max 50KG','Green Lion Digital Luggage Scale - Max 50KG Capacity','Compact digital luggage scale with 50KG capacity and digital display. Essential travel accessory.',15,'https://placehold.co/500x500/0f172a/ffffff?text=GL+Luggage+Scale',4.7,'Accessories','Green Lion',true,'["50KG maximum capacity","Digital display","Compact & portable","Easy to use","Perfect for travel"]','[{"label":"Max Capacity","value":"50KG"},{"label":"Display","value":"Digital"},{"label":"Design","value":"Compact & Portable"}]','["Travel"]'),
(5012,'Green Lion Dual Kitchen Scale','Green Lion Dual Kitchen Scale - Large & Small Platforms, Tare Function','Precision dual kitchen scale with large (5kg) and small (500g) platforms, tare function, auto shut-off, and digital display.',30,'https://placehold.co/500x500/0f172a/ffffff?text=GL+Kitchen+Scale',4.8,'Accessories','Green Lion',true,'["Large platform: 5kg/11lbs (1g division)","Small platform: 500g/17.64oz (0.1g division)","Tare function","Auto shut-off: 120 seconds","Low battery indicator","Overload indicator","3*AAA battery"]','[{"label":"Large Platform","value":"5kg (1g)"},{"label":"Small Platform","value":"500g (0.1g)"},{"label":"Auto Off","value":"120 seconds"},{"label":"Battery","value":"3*AAA"}]','["Kitchen"]'),
(5013,'Green Lion Elegant Pouch','Green Lion Elegant Pouch - Waterproof Travel Organizer','Premium waterproof travel organizer with elastic cable organizers, multiple pockets, reinforced handle, and double polyester material.',20,'https://placehold.co/500x500/0f172a/ffffff?text=GL+Elegant+Pouch',4.7,'Accessories','Green Lion',true,'["Waterproof & quick-dry interior","Double polyester material","Elastic cable organizers","Multi pockets","Reinforced handle","Shock resistant","Size: 230x117x85mm"]','[{"label":"Size","value":"230x117x85mm"},{"label":"Material","value":"Double Polyester"},{"label":"Features","value":"Waterproof, Quick-Dry"},{"label":"Handle","value":"Reinforced"}]','["Travel","Storage"]'),
(5014,'Green Lion Sigma Laptop Sleeve Bag','Green Lion Sigma Laptop Sleeve Bag - 14.1\" Multi-Padded Protection','Protective 14.1" laptop sleeve with multi-padded protection, 300D mixed cotton polyester exterior, and durable zipper.',25,'https://placehold.co/500x500/0f172a/ffffff?text=GL+Sigma+Bag',4.6,'Accessories','Green Lion',true,'["14.1\" laptop sleeve","Multi-padded protection","300D mixed cotton polyester exterior","210D polyester interior","Durable zipper","Lightweight design","360x20x265mm dimensions"]','[{"label":"Laptop Size","value":"14.1\""},{"label":"Dimensions","value":"360x20x265mm"},{"label":"Outer Material","value":"300D mixed cotton polyester"},{"label":"Interior","value":"210D polyester"}]','["Laptop Accessories"]'),
(5015,'Green Lion Orbit Sleeve Laptop Bag','Green Lion Orbit Sleeve Laptop Bag - Premium Protection','Stylish premium laptop sleeve with quality materials, elegant design, and soft interior for professional protection.',35,'https://placehold.co/500x500/0f172a/ffffff?text=GL+Orbit+Bag',4.7,'Accessories','Green Lion',true,'["Premium protection","Quality materials","Elegant orbit design","Soft interior","Durable construction"]','[{"label":"Protection","value":"Premium padded"},{"label":"Design","value":"Elegant, Orbit style"}]','["Laptop Accessories"]'),
(5016,'Green Lion LED Table Lamp','Green Lion LED Table Lamp - Adjustable Brightness','Modern LED table lamp with adjustable brightness, flexible design, touch control, and energy-efficient LED technology.',27,'https://placehold.co/500x500/0f172a/ffffff?text=GL+LED+Lamp',4.8,'Accessories','Green Lion',true,'["Adjustable brightness","Energy efficient LED","Flexible design","Touch control","Modern style"]','[{"label":"Type","value":"LED Table Lamp"},{"label":"Brightness","value":"Adjustable"},{"label":"Control","value":"Touch"},{"label":"Design","value":"Flexible, Modern"}]','["Home & Office"]'),
(5017,'Green Lion M6-Rotating Stand','Green Lion M6-Rotating Stand - Three-Axis Design','Three-axis 360° rotating phone stand with adjustable angles for optimal viewing. Perfect for video calls and hands-free use.',12,'https://placehold.co/500x500/0f172a/ffffff?text=GL+M6+Stand',4.6,'Accessories','Green Lion',true,'["Three-axis design","360° rotation","Adjustable angles","Stable base","Universal compatibility"]','[{"label":"Design","value":"Three-Axis Rotating"},{"label":"Rotation","value":"360°"},{"label":"Compatibility","value":"Universal smartphones"}]','["Phone Accessories"]'),
(5018,'Green Lion M5-Foldable Phone & Tablet Holder','Green Lion M5-Foldable Phone & Tablet Holder - Adjustable Stand','Versatile foldable stand for phones and tablets with adjustable height, multiple angles, and non-slip base.',12,'https://placehold.co/500x500/0f172a/ffffff?text=GL+M5+Holder',4.7,'Accessories','Green Lion',true,'["Foldable design","Phone & tablet compatible","Adjustable height","Multiple angles","Non-slip base","Portable & compact"]','[{"label":"Compatibility","value":"Phones & Tablets"},{"label":"Design","value":"Foldable"},{"label":"Adjustability","value":"Height and angle"},{"label":"Base","value":"Non-slip"}]','["Phone Accessories","Tablet Accessories"]'),
(5019,'Green Lion New York Gimbal Smart Face Tracking','Green Lion New York Gimbal - 3-Axis Stabilization with Face Tracking','Professional 3-axis gimbal with smart face tracking, OLED display, built-in fill light, 7-10 hours battery, and 5 shooting modes.',85,'https://placehold.co/500x500/0f172a/ffffff?text=GL+Gimbal',4.9,'Accessories','Green Lion',true,'["3-axis stabilization (Pan 310°/Roll 330°/Tilt 76°)","Smart face tracking","OLED display","Built-in fill light","5 shooting modes: LPF/FF/POV/DM/GO","7-10 hours working time","3200mAh battery","≤250g load capacity","Focus & zoom control"]','[{"label":"Stabilization","value":"3-Axis"},{"label":"Pan","value":"310°"},{"label":"Roll","value":"330°"},{"label":"Tilt","value":"76°"},{"label":"Battery","value":"3200mAh"},{"label":"Working Time","value":"7-10 Hours"},{"label":"Load","value":"≤250g"}]','["Camera Accessories","Photography"]'),
(5020,'Green Lion Magselfie Selfie Stick Tripod','Green Lion Magselfie Selfie Stick Tripod - MagSafe Compatible with Remote','MagSafe-compatible selfie stick tripod with wireless remote, 360° rotation, extends to 1045mm, and aluminium alloy build.',30,'https://placehold.co/500x500/0f172a/ffffff?text=GL+Magselfie',4.7,'Accessories','Green Lion',true,'["MagSafe compatible","Wireless remote (CR1632)","360° rotation","Extends to 1045mm","Folds to 210mm","Aluminium alloy rod","54x58x210mm size"]','[{"label":"Extended Length","value":"1045mm"},{"label":"Folded","value":"210mm"},{"label":"Material","value":"Aluminium Alloy"},{"label":"Rotation","value":"360°"},{"label":"Remote","value":"Wireless CR1632"}]','["Phone Accessories","Photography"]'),
(5021,'Green Lion G-Kid 20 Kids Tablet','Green Lion G-Kid 20 Kids Tablet - 10.95\" Android 15, 6GB+128GB with Stylus','Kids tablet with 10.95" IPS screen, Android 15, Spreadtrum T606 octa-core, 6GB+128GB, 7000mAh, Bluetooth keyboard, stylus pen, and flip case.',100,'https://placehold.co/500x500/0f172a/ffffff?text=GL+G-Kid+20',4.8,'Accessories','Green Lion',true,'["10.95\" IPS 1920x1200 display","Spreadtrum T606 Octa-core 1.6GHz","6GB RAM, 128GB storage","Android 15.0","7000mAh battery","2G/3G/4G + 5G WiFi","Bluetooth 5.0","13MP rear + 5MP front camera","TF card up to 1TB","Bluetooth keyboard included","Stylus pen included","Flip case included"]','[{"label":"Display","value":"10.95\" IPS, 1920x1200"},{"label":"CPU","value":"T606 Octa-core 1.6GHz"},{"label":"RAM","value":"6GB"},{"label":"Storage","value":"128GB"},{"label":"OS","value":"Android 15.0"},{"label":"Battery","value":"7000mAh"},{"label":"Cameras","value":"13MP + 5MP"},{"label":"Connectivity","value":"4G, 5G WiFi, BT 5.0"}]','["Tablets","Kids Electronics"]'),
(5022,'Green Lion G-20 Ultra Tablet','Green Lion G-20 Ultra - 10.1\" Full HD Tablet, 6GB+128GB with 4G','10.1" Full HD tablet with Spreadtrum T606 8-core, 6GB RAM, 128GB storage, 4G, 5000mAh, 13MP camera, Bluetooth keyboard, and flip cover.',150,'https://placehold.co/500x500/0f172a/ffffff?text=GL+G20+Ultra',4.7,'Accessories','Green Lion',true,'["10.1\" FHD IPS 1920x1200","Spreadtrum T606 8-Core","6GB RAM, 128GB storage","Android 13.0","5000mAh Li-Polymer battery","4G connectivity","Dual SIM","13MP rear + 5MP front camera","Bluetooth keyboard included","Flip cover included"]','[{"label":"Display","value":"10.1\" FHD IPS"},{"label":"CPU","value":"T606 8-Core"},{"label":"RAM","value":"6GB"},{"label":"Storage","value":"128GB"},{"label":"OS","value":"Android 13.0"},{"label":"Battery","value":"5000mAh"},{"label":"Connectivity","value":"4G, Dual SIM"}]','["Tablets"]'),
(5023,'Green Lion Sevilla Wireless Neckband','Green Lion Sevilla Wireless Neckband - Bluetooth 5.4, 21 Hours Playtime','Comfortable wireless neckband with Bluetooth 5.4, 21 hours talk time, 75 days standby, and 12m effective range.',20,'https://placehold.co/500x500/0f172a/ffffff?text=GL+Sevilla',4.6,'Accessories','Green Lion',true,'["Bluetooth V5.4","180mAh battery","21 hours talking time (80% vol)","20 hours playtime","75 days standby","12m effective range","5V/150mA charging"]','[{"label":"Bluetooth","value":"V5.4"},{"label":"Battery","value":"180mAh"},{"label":"Talk Time","value":"21 hours"},{"label":"Playtime","value":"20 hours"},{"label":"Standby","value":"75 Days"},{"label":"Range","value":"12m"}]','["Audio","Headphones"]'),
(5024,'Green Lion Manchester True Wireless Earbuds','Green Lion Manchester TWS Earbuds - Bluetooth 5.4, IPX3 Waterproof','True wireless earbuds with Bluetooth 5.4, IPX3 waterproof, low latency mode, 4 hours playtime, Type-C charging. Available in Black and Silver.',20,'https://placehold.co/500x500/0f172a/ffffff?text=GL+Manchester',4.7,'Accessories','Green Lion',true,'["Bluetooth V5.4","IPX3 waterproof","Low latency mode","4 hours playtime","4.5 hours talk time","25mAh earbuds + 200mAh case","Type-C charging (70 min)","8mm speaker","12m range","Standby: 2000 hours"]','[{"label":"Bluetooth","value":"V5.4"},{"label":"Speaker","value":"8mm"},{"label":"Playtime","value":"4 hours"},{"label":"Case Battery","value":"200mAh"},{"label":"Charging","value":"70 minutes"},{"label":"Waterproof","value":"IPX3"}]','["Audio","Earbuds"]'),
(5025,'Green Lion River True Wireless Earbuds','Green Lion River TWS Earbuds - ANC+ENC, Bluetooth 5.4, 6-7 Hours Playtime','Premium TWS earbuds with ANC+ENC (-42dB), 13mm speakers, smart in-ear detection, transparency mode, IPX4, Bluetooth 5.4. Available in Black, White, Rose Gold.',35,'https://placehold.co/500x500/0f172a/ffffff?text=GL+River+TWS',4.8,'Accessories','Green Lion',true,'["Bluetooth V5.4","ANC+ENC: -42dB noise reduction","13mm speaker","Smart in-ear detection","Transparency mode","6-7 hours playtime","IPX4 waterproof","40mAh earbuds + 400mAh case","1.5 hour charging","10-15m range"]','[{"label":"Bluetooth","value":"V5.4"},{"label":"Speaker","value":"13mm"},{"label":"ANC","value":"-42dB"},{"label":"Playtime","value":"6-7 hours"},{"label":"Case Battery","value":"400mAh"},{"label":"Charging","value":"1.5 hours"},{"label":"Waterproof","value":"IPX4"}]','["Audio","Earbuds"]'),
(5026,'Green Lion ECHO ANC Headphone','Green Lion ECHO ANC Zero Sound. Zero Noise Headphone - 36 Hours, AUX Support','Over-ear ANC headphones with 36 hours BT playtime (25hrs ANC+BT), 40mm driver, AUX support, Bluetooth 5.3, JL 7006F4 chip. Available in Black and Beige.',28,'https://placehold.co/500x500/0f172a/ffffff?text=GL+ECHO+ANC',4.8,'Accessories','Green Lion',true,'["Bluetooth V5.3","ANC active noise cancellation","40mm driver","36 hours BT playtime","25 hours ANC+BT playtime","AUX support","2.5 hour charging","10m range","32Ω impedance","105dB sensitivity"]','[{"label":"Bluetooth","value":"V5.3"},{"label":"Driver","value":"40mm"},{"label":"BT Playtime","value":"36 hours"},{"label":"ANC Playtime","value":"25 hours"},{"label":"Charging","value":"2.5 hours"},{"label":"Impedance","value":"32Ω"}]','["Audio","Headphones"]'),
(5027,'Green Lion Rhythm X50 ANC Wireless Headphone','Green Lion Rhythm X50 ANC - Bluetooth 6.0, 30-50 Hours Playtime, Metal Body','Premium ANC wireless headphones with Bluetooth 6.0, 30-50 hours playtime, high-grade metal body, foldable design, Type-C charging. Available in Black and Brown.',40,'https://placehold.co/500x500/0f172a/ffffff?text=GL+Rhythm+X50',4.9,'Accessories','Green Lion',true,'["Bluetooth V6.0","ANC: 30±3 dB noise reduction","40mm speaker","30-50 hours playtime","High-grade metal + ABS body","Foldable design","1.5 hour charging","Type-C charging","Voice assistant","350mAh battery"]','[{"label":"Bluetooth","value":"V6.0"},{"label":"Speaker","value":"40mm"},{"label":"Battery","value":"350mAh"},{"label":"Playtime","value":"30-50 hours"},{"label":"ANC","value":"30±3dB"},{"label":"Charging","value":"1.5 hours"},{"label":"Material","value":"ABS + Metal"}]','["Audio","Headphones"]'),
(5028,'Green Lion Jupiter Bluetooth Speaker with Table Lamp','Green Lion Jupiter Speaker - 15W Wireless Charging, RGB Lights, Bluetooth','Multifunctional speaker + table lamp with 15W wireless charging, 100 RGB LEDs (9 color modes), 2 hours playtime, and 3000K color temperature.',59.99,'https://placehold.co/500x500/0f172a/ffffff?text=GL+Jupiter',4.8,'Accessories','Green Lion',true,'["15W/10W/7.5W/5W wireless charging","100 RGB LEDs","9 color modes","50-300 lm brightness","3000K color temperature","2 hours working time","1.5 hours charging","Bluetooth speaker","<20m range"]','[{"label":"Wireless Charging","value":"15W max"},{"label":"LEDs","value":"100 RGB"},{"label":"Color Modes","value":"9"},{"label":"Brightness","value":"50-300 lm"},{"label":"Color Temp","value":"3000K"},{"label":"Working Time","value":"2 Hours"}]','["Audio","Speakers","Home & Office"]'),
(5029,'Green Lion Porto Wireless Speaker','Green Lion Porto Speaker - IPX6 Waterproof, 8W Output, RGB Light, Extra Bass','Portable IPX6 waterproof wireless speaker with 8W output, extra bass, RGB lighting, 6-7 hours playtime, and Bluetooth 5.2.',44.99,'https://placehold.co/500x500/0f172a/ffffff?text=GL+Porto+Speaker',4.7,'Accessories','Green Lion',true,'["IPX6 waterproof","8W output power","Extra bass enhancement","RGB light effect","6-7 hours playtime","Bluetooth 5.2","1200mAh battery","10m range","120Hz-18KHz frequency"]','[{"label":"Bluetooth","value":"BT 5.2"},{"label":"Output","value":"8W"},{"label":"Battery","value":"1200mAh"},{"label":"Playtime","value":"6-7 hours"},{"label":"Waterproof","value":"IPX6"}]','["Audio","Speakers"]'),
(5030,'Green Lion Active 49 - 49MM Smart Watch','Green Lion Active 49 Smartwatch - 2.11\" IPS Display, IP68 Waterproof','Feature-packed 49MM smartwatch with 2.11" IPS display, IP68, wireless charging, Bluetooth 3.0+5.1, 2-3 days working time, 10 days standby.',35,'https://placehold.co/500x500/0f172a/ffffff?text=GL+Active+49',4.7,'Accessories','Green Lion',true,'["2.11-inch IPS display (320x384)","IP68 waterproof","Wireless charging","Bluetooth 3.0+5.1","370mAh battery","2-3 days working time","10 days standby","1GB flash storage"]','[{"label":"Display","value":"2.11\" IPS, 320x384"},{"label":"Battery","value":"370mAh"},{"label":"Working Time","value":"2-3 Days"},{"label":"Standby","value":"10 Days"},{"label":"Bluetooth","value":"3.0+5.1"},{"label":"Waterproof","value":"IP68"},{"label":"Charging","value":"Wireless"}]','["Wearables","Smartwatches"]'),
(5031,'Green Lion Ultimate 10 46MM Smart Watch','Green Lion Ultimate 10 Smartwatch - 2.07\" AMOLED, IP68 Waterproof','Premium 46MM smartwatch with 2.07" AMOLED display, IP68, wireless charging, advanced health tracking, 2-3 days battery, 10 days standby.',50,'https://placehold.co/500x500/0f172a/ffffff?text=GL+Ultimate+10',4.8,'Accessories','Green Lion',true,'["2.07-inch AMOLED display (410x480)","IP68 waterproof","Wireless charging","Bluetooth 3.0+5.1","375mAh battery","2-3 days working time","10 days standby","Advanced health tracking"]','[{"label":"Display","value":"2.07\" AMOLED, 410x480"},{"label":"Battery","value":"375mAh"},{"label":"Working Time","value":"2-3 Days"},{"label":"Standby","value":"10 Days"},{"label":"Bluetooth","value":"3.0+5.1"},{"label":"Waterproof","value":"IP68"}]','["Wearables","Smartwatches"]'),
(5032,'Green Lion Track Fit Smart Watch','Green Lion Track Fit Smartwatch - Fitness Tracking & Health Monitoring','Fitness-focused smartwatch with comprehensive health tracking, multiple sports modes, heart rate monitoring, sleep tracking, and smart notifications. Black & Silver.',27,'https://placehold.co/500x500/0f172a/ffffff?text=GL+Track+Fit',4.6,'Accessories','Green Lion',true,'["Comprehensive health tracking","Multiple sports modes","Heart rate monitoring","Sleep tracking","Water resistant","Long battery life","Smart notifications"]','[{"label":"Health","value":"Heart Rate, Sleep, Activity"},{"label":"Sports Modes","value":"Multiple"},{"label":"Notifications","value":"Call, Message, App"},{"label":"Water Resistance","value":"Yes"}]','["Wearables","Smartwatches","Fitness"]'),
(5033,'Green Lion Ultimate 41 Smart Watch','Green Lion Ultimate 41 Smartwatch - 1.75\" IPS, Always On Display, Zinc Alloy','Elegant 41MM smartwatch with 1.75" IPS, always-on display, zinc alloy body, extra strap, 3-5 days battery. Black, Silver, and Pink.',28,'https://placehold.co/500x500/0f172a/ffffff?text=GL+Ultimate+41',4.8,'Accessories','Green Lion',true,'["1.75-inch IPS (240x296)","Always On Display","Zinc alloy body","Full-touch screen","Gesture operation","Extra strap included","Bluetooth 5.0","3-5 days working time","10-15 days standby","200mAh battery"]','[{"label":"Display","value":"1.75\" IPS, 240x296"},{"label":"Body","value":"Zinc Alloy"},{"label":"Battery","value":"200mAh"},{"label":"Working Time","value":"3-5 Days"},{"label":"Standby","value":"10-15 Days"},{"label":"Bluetooth","value":"5.0"},{"label":"Features","value":"Always On Display, Gesture"}]','["Wearables","Smartwatches"]'),
(5034,'Green Lion Bedside Clock with Wireless Charger','Green Lion Bedside Clock - 15W Wireless Charging, Night Light, 14 Display Styles','Multifunctional bedside clock with 15W wireless charging, ambient night light, 14 display styles, wood grain finish, and touch control.',30,'https://placehold.co/500x500/0f172a/ffffff?text=GL+Bedside+Clock',4.9,'Accessories','Green Lion',true,'["15W max wireless charging","14 display styles","Ambient night light","3 brightness levels","3000±300K color temperature","Wood grain finish","Touch & switch control","12H/24H clock","Type-C power input","5pcs LED beads"]','[{"label":"Wireless Charging","value":"15W Max"},{"label":"Power Input","value":"9V/3A, 27W Max"},{"label":"Display Styles","value":"14"},{"label":"Brightness","value":"3 Levels"},{"label":"Color Temp","value":"3000±300K"},{"label":"Material","value":"ABS, Wood Grain"}]','["Home & Office","Charging"]'),
(5035,'Green Lion Mini DC UPS 10000mAh','Green Lion Mini DC UPS - 10000mAh with AC Input, Universal Compatibility','Uninterruptible power supply with 10000mAh, AC input (90-264V), multiple DC/USB outputs, POE support, 8 hours working time, 5 hours charging. Universal compatibility.',30,'https://placehold.co/500x500/0f172a/ffffff?text=GL+Mini+UPS',4.7,'Accessories','Green Lion',true,'["10000mAh battery","AC input: 90-264V, 50Hz, 0.4A","DC1 output: 5V/2A","DC2 output: 9V/2A or 12V/2A","POE output: 24V/0.5A","USB-A output: 5V/3A","5 hours charging time","8 hours working time","Universal compatibility"]','[{"label":"Battery","value":"10000mAh"},{"label":"AC Input","value":"90-264V, 50Hz"},{"label":"DC1","value":"5V/2A"},{"label":"DC2","value":"9V/2A, 12V/2A"},{"label":"POE","value":"24V/0.5A"},{"label":"USB-A","value":"5V/3A"},{"label":"Working Time","value":"8 Hours"}]','["Charging","Power"]')
ON CONFLICT (legacy_override_id) DO UPDATE SET
  name=EXCLUDED.name, title=EXCLUDED.title, description=EXCLUDED.description,
  price=EXCLUDED.price, primary_image_url=EXCLUDED.primary_image_url,
  rating=EXCLUDED.rating, category=EXCLUDED.category, brand=EXCLUDED.brand,
  features=EXCLUDED.features, specifications=EXCLUDED.specifications,
  secondary_categories=EXCLUDED.secondary_categories, updated_at=NOW();

COMMIT;

-- ─────────────────────────────────────────────────────────────────────────────
-- DONE
-- After running this:
--   1. Restart your Express server (npm run dev in server/)
--   2. The CatalogContext will fetch all products from /api/public/products
--   3. Each product OVERRIDES its static version (via legacy_override_id)
--   4. Update placeholder image URLs through: Admin → Products → Edit → Upload
-- ─────────────────────────────────────────────────────────────────────────────
